# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[benchmark]
name = "KMeans"
short_name = "kmeans"
relative_path = "kmeans"
module_name = "kmeans"
func_name = "kmeans"
kind = "microbenchmark"
domain = "Machine Learning"
input_args = [
    "arrayP",
    "arrayPclusters",
    "arrayC",
    "arrayCnumpoint",
    "niters",
]
array_args = [
    "arrayP",
    "arrayPclusters",
    "arrayC",
    "arrayCnumpoint",
]
output_args = [
    "arrayPclusters",
    "arrayC",
    "arrayCnumpoint",
]
# TODO: remove once fixed. Fails randomly
# remove numba_dpex_k once atomics on SLM is implemented
expected_failure_implementations = ["numba_mlir_k", "numba_dpex_k"]

[benchmark.parameters.S]
npoints = 4096
niters = 10
seed = 7777777
ndims = 2
ncentroids = 10

[benchmark.parameters.M16Gb]
npoints = 1048576
niters = 30
seed = 7777777
ndims = 2
ncentroids = 10

[benchmark.parameters.M]
npoints = 1048576
niters = 30
seed = 7777777
ndims = 2
ncentroids = 10

[benchmark.parameters.L]
npoints = 2097152
niters = 30
seed = 7777777
ndims = 2
ncentroids = 10

[benchmark.init]
func_name = "initialize"
types_dict_name="types_dict"
precision="double"
input_args = [
    "npoints",
    "niters",
    "seed",
    "ndims",
    "ncentroids",
    "types_dict",
]
output_args = [
    "arrayP",
    "arrayPclusters",
    "arrayC",
    "arrayCnumpoint",
]
