# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dpbench-dev
channels:
  - dppy/label/dev
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - tomli
  - alembic
  - sqlalchemy
  - py-cpuinfo
  - scipy
  - scikit-learn
  - versioneer
  - pandas
  - numpy
  - numba
  - dpctl
  - dpnp
  - numba-dpex>=0.23.0*
  - dpcpp_linux-64
  - dpcpp-cpp-rt
  - cython
  - cmake
  - ninja
  - scikit-build
  # https://github.com/scikit-build/scikit-build/issues/981
  - setuptools>=42,<64
  - pybind11
  - libgcc-ng
  - libstdcxx-ng
  - libgomp
