# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dpbench-dev
channels:
  - dppy/label/dev
  - conda-forge
  - intel
  - nodefaults
dependencies:
  - pip
  - tomli
  - alembic
  - sqlalchemy
  - py-cpuinfo
  - scipy
  - scikit-learn
  - versioneer
  - pandas
  - intel::numpy
  - numba
  - dpctl
  - dpnp
  - numba-dpex
  # TODO: fix issues on conda-forge build
  - intel::dpcpp_linux-64==2024.0.0
  - intel::dpcpp-cpp-rt==2024.0.0
  - cython
  - cmake
  - ninja
  - scikit-build
  # https://github.com/scikit-build/scikit-build/issues/981
  - setuptools>=42,<64
  - pybind11
  - libgcc-ng
  - libstdcxx-ng
  - libgomp
