# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dpbench-dev
channels:
  - dppy/label/dev
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - tomli
  - alembic
  - sqlalchemy
  - py-cpuinfo
  - scipy
  - scikit-learn
  - versioneer
  - pandas
  - intel-opencl-rt # need for set-intel-ocl-icd-registry.ps1
  - numpy
  - numba
  - dpctl
  - dpnp
  - numba-dpex>=0.23.0*
