# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dpbench-dev
channels:
  - dppy/label/dev
  - conda-forge
  - intel
  - nodefaults
dependencies:
  - pip
  - tomli
  - alembic
  - sqlalchemy
  - py-cpuinfo
  - scipy
  - scikit-learn
  - versioneer
  - pandas
  - intel::numpy
  - numba
  - dpctl
  - dpnp
  - numba-dpex
  - numba-mlir
  # TODO: switch to conda-forge, but it results in broken OpenCL rt (see below)
  # - conda-forge::dpcpp_win-64
  - intel::dpcpp_win-64==2024.0.0
  # fixing cmake version here, because we need to apply patch for IntelLLVM
  - cmake==3.26*
  - cython
  - scikit-build
  # TODO: switch to khronos, sycl-ls works fine, but dpctl can't select device.
  # set's OpenCL runtime (better version of intel-opencl-rt)
  # - khronos-opencl-icd-loader
  - intel::intel-opencl-rt # need for set-intel-ocl-icd-registry.ps1
  # https://github.com/scikit-build/scikit-build/issues/981
  - setuptools>=42,<64
  - pybind11
  - pylint
