# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{% set pyproject = load_file_data('pyproject.toml') %}
{% set py_deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set py_build_deps = pyproject.get('build-system', {}).get('requires', []) %}
{% set project_scripts = pyproject.get('project', {}).get('scripts', {}) %}

package:
  name: dpbench
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
        - WHEELS_OUTPUT_FOLDER
    entry_points:
        {% for script, module in project_scripts | dictsort %}
        - {{ script ~ " = " ~ module }}
        {% endfor %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('dpcpp') }}
    # This is required to get compatible headers with the system installed glibc
    - sysroot_linux-64 >=2.28  # [linux]
  host:
    - python
    - pip
    {% for dep in py_build_deps %}
      {% if dep.startswith('ninja') %}
    - {{ dep.split(';')[0] }} # [not win]
      {% elif dep.startswith('cmake') %}
    - cmake=3.26 # [win]
    - {{ dep }} # [not win]
      {% elif dep.startswith('build>=') %}
    - {{ 'python-' ~ dep }}
      {% else %}
    - {{ dep|replace('_','-') }}
      {% endif %}
    {% endfor %}
  run:
    {% for dep in py_deps %}
    - {{ dep|replace('_','-') }}
    {% endfor %}

test:
  commands:
    - dpbench --help

about:
  home: https://github.com/IntelPython/dpbench
  license: Apache 2.0
  license_file: LICENSE
  description: |
      <strong>LEGAL NOTICE: Use of this software package is subject to the
      software license agreement (as set forth above, in the license section of
      the installed Conda package and/or the README file) and all notices,
      disclaimers or license terms for third party or open source software
      included in or with the software.</strong>
      <br/><br/>
      EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
      <br/><br/>
extra:
  recipe-maintainers:
    - Intel Python
