name: Run benchmark

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: echo "Hello world!"
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Command: ${{ github.event.inputs.command }}"
